-- =============================================
-- SALA CERTA REDESIGN - MIGRATION SCRIPT
-- Run this AFTER importing the original salacerta.sql
-- =============================================

-- 1. USUARIO: Renomear SETOR -> USUARIO_DEPARTAMENTO
ALTER TABLE USUARIO CHANGE SETOR USUARIO_DEPARTAMENTO VARCHAR(100) DEFAULT NULL;

-- 2. USUARIO: Remover USUARIO_CURSO
ALTER TABLE USUARIO DROP COLUMN USUARIO_CURSO;

-- 3. USUARIO: Adicionar USUARIO_CARGO
ALTER TABLE USUARIO ADD COLUMN USUARIO_CARGO VARCHAR(100) DEFAULT NULL AFTER USUARIO_DEPARTAMENTO;

-- 4. USUARIO: Popular USUARIO_CARGO para registros existentes
UPDATE USUARIO SET USUARIO_CARGO = 'Funcionario' WHERE USUARIO_CARGO IS NULL;

-- 5. RESERVA_SALA: Adicionar campos de recorrencia
ALTER TABLE RESERVA_SALA ADD COLUMN RECORRENCIA ENUM('semanal', 'quinzenal', 'mensal') DEFAULT NULL;
ALTER TABLE RESERVA_SALA ADD COLUMN RECORRENCIA_FIM DATE DEFAULT NULL;
ALTER TABLE RESERVA_SALA ADD COLUMN RESERVA_PAI_ID INT DEFAULT NULL;
ALTER TABLE RESERVA_SALA ADD KEY idx_reserva_pai (RESERVA_PAI_ID);
ALTER TABLE RESERVA_SALA ADD CONSTRAINT fk_reserva_pai FOREIGN KEY (RESERVA_PAI_ID) REFERENCES RESERVA_SALA(RESERVA_ID) ON DELETE SET NULL;

-- 6. NOTIFICACAO: Nova tabela
CREATE TABLE IF NOT EXISTS NOTIFICACAO (
    NOTIFICACAO_ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    TIPO ENUM('confirmacao', 'lembrete', 'cancelamento', 'conflito') NOT NULL,
    MENSAGEM TEXT NOT NULL,
    LIDA TINYINT(1) DEFAULT 0,
    CRIADO_EM DATETIME DEFAULT CURRENT_TIMESTAMP,
    RESERVA_ID INT DEFAULT NULL,
    KEY idx_notif_usuario_lida (USUARIO_ID, LIDA, CRIADO_EM),
    CONSTRAINT fk_notif_usuario FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID) ON DELETE CASCADE,
    CONSTRAINT fk_notif_reserva FOREIGN KEY (RESERVA_ID) REFERENCES RESERVA_SALA(RESERVA_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. CONFIGURACAO_NOTIFICACAO: Nova tabela
CREATE TABLE IF NOT EXISTS CONFIGURACAO_NOTIFICACAO (
    CONFIG_ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID INT NOT NULL UNIQUE,
    NOTIF_CONFIRMACAO TINYINT(1) DEFAULT 1,
    NOTIF_LEMBRETE TINYINT(1) DEFAULT 1,
    NOTIF_CANCELAMENTO TINYINT(1) DEFAULT 1,
    CONSTRAINT fk_config_usuario FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
